April 2019, nearly complete
melbournecocoa/mc-intro-slides-2018 pull request #9
Opened 2019-04-10 13:36 UTC by jessedc

2019-04-10 13:42 UTC, mattdelves commented on intro-2019-04.md
> +- Looking for help to share responsibilities and chape CocoaHeads going forward
s/chape/shape

2019-04-10 13:42 UTC, mattdelves commented on intro-2019-04.md
> +- BYO laptop and your iOS, macOS, tvOS, watchOS Android project
, after watchOS

2019-04-10 20:27 UTC, tupps commented on intro-2019-04.md
> +- Alchohol free, :pizza: provided
Is 🍣 possible?

2019-04-10 20:27 UTC, tupps commented on intro-2019-04.md
> +- Doors open at 6:00pm
5:45

2019-04-10 20:27 UTC, tupps commented on intro-2019-04.md
> +- Introductions from 6:30pm
6:15

2019-04-10 20:28 UTC, tupps commented on intro-2019-04.md
> +## April 17 @ Cognizant from 6:00pm
5:45

2019-04-11 05:25 UTC, kevinoneill requested changes

2019-04-11 05:25 UTC, kevinoneill commented on intro-2019-04.md
> +7:00 - 7:25 | Kevin O'neal | iOS and TEA
Kevin O'Neill

2019-04-17 03:33 UTC, merged